POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZDM1MGY1ZGY3YWU3N2Q1OWZjNmY1YiIsImlhdCI6MTYyNDQ2MjQ2MiwiZXhwIjoxNjI0NDY2MDYyfQ.HvZKVwC98OiZv1HcqzE9NEU1BbLkBXfLG3zbtyEVbL4

{
    "title": "Hoger Fuger II",
    "author": "12345678",
    "url": "http://example.com",
    "likes": 2
}
